import type { Metadata } from "next";
import { nunito, poppins, jetbrainsMono } from "@/utils/fonts"; // إن فصلتها في ملف منفصل
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${nunito.className} ${poppins.className} ${jetbrainsMono.className}`}>
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
